let User,CustomErrorHandler;_6f4‍.x([["default",()=>_6f4‍.o]]);_6f4‍.w("../../models",[["User",["User"],function(v){User=v}]]);_6f4‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
    async me(req, res, next) {
        try {
            const user = await User.findOne({ _id: req.user._id }).select('-password -updatedAt -__v');
            if (!user) {
                return next(CustomErrorHandler.notFound());
            }
            res.json(user);
        } catch(err) {
           return next(err);
        }
    }
};

_6f4‍.d(userController);